/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package belajarcrud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Azriel
 */
public class FormSiswa extends javax.swing.JPanel {

    /**
     * Creates new form FormSiswa
     */
    public FormSiswa() {
        initComponents();
        koneksi();
        display();
    }
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement statSiswa;
    Boolean ada = false;
    
    private void koneksi() {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:6033/crud_java?useSSL=false";
            String user = "root";
            String pass = "password";
            con = DriverManager.getConnection(url, user, pass);
            statSiswa = con.createStatement(rs.TYPE_SCROLL_SENSITIVE, rs.CONCUR_UPDATABLE);
            rs = statSiswa.executeQuery("select * from siswa");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.exit(0);
        }
    }
    
    private void display() {
        try {
            String sql = "select * from siswa";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void Reset() {
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NIS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 65, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 62, 168, -1));

        jLabel2.setText("FORM SISWA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 24, -1, -1));

        jLabel3.setText("Nama");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 105, -1, -1));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 102, 168, -1));

        jLabel4.setText("Rombel");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 145, -1, -1));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 142, 168, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 58, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 99, -1, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 58, -1, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 99, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 140, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "nis", "nama", "rombel"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 469, 162));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            koneksi();
            statSiswa = con.createStatement();
            String nisText = jTextField1.getText();
            int nisValue = Integer.parseInt(nisText);
            String SQL = "INSERT INTO siswa (nis, nama, rombel) VALUES ('"+nisValue+"', '"+jTextField2.getText()+"', '"+jTextField3.getText()+"');";
            statSiswa.executeUpdate(SQL);
            display();
            statSiswa.close();
            con.close();
            Reset();
            JOptionPane.showMessageDialog(null, "berhasil simpan data siswa");
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            koneksi(); 
            String nis = jTextField1.getText(); 
            String nama = jTextField2.getText(); 
            String rombel = jTextField3.getText(); 

            String SQL = "UPDATE siswa SET nama = ?, rombel = ? WHERE nis = ?";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, nama); 
            pst.setString(2, rombel); 
            pst.setString(3, nis); 

            int rowsAffected = pst.executeUpdate(); 

            if (rowsAffected > 0) {
                display(); 
                Reset(); 
                JOptionPane.showMessageDialog(null, "Berhasil edit");
            } else {
                JOptionPane.showMessageDialog(null, "Gagal edit");
            }

            pst.close();
            con.close();
        } catch (Exception exc) {
            exc.printStackTrace(); 
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
        koneksi(); 
        int row = jTable1.getSelectedRow(); 

        if (row != -1) {
            String nis = jTable1.getModel().getValueAt(row, 0).toString(); 

            String query = "SELECT * FROM siswa WHERE nis = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, nis);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) { 
                String id = rs.getString("nis");
                jTextField1.setText(id);
                String nama = rs.getString("nama");
                jTextField2.setText(nama);
                String rombel = rs.getString("rombel");
                jTextField3.setText(rombel);
            }
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            koneksi(); 
            String nis = jTextField1.getText(); 

            String SQL = "DELETE FROM siswa WHERE nis = ?";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, nis); 

            int rowsAffected = pst.executeUpdate(); 

            if (rowsAffected > 0) {
                display(); 
                JOptionPane.showMessageDialog(null, "Berhasil hapus"); 
            } else {
                JOptionPane.showMessageDialog(null, "Gagal hapus");
            }

            pst.close();
            con.close();
        } catch (Exception exc) {
            exc.printStackTrace();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        Reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
